/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Anggota;
import service.AnggotaRepo;

/**
 *
 * @author PKane_NS
 */
public class ui extends javax.swing.JFrame {

    private final AnggotaRepo repo = new AnggotaRepo();
    private DefaultTableModel tabmode;
    /**
     * Creates new form ui
     */
    public ui() {
        initComponents();
        try {
            showData();
        } catch (Exception e) {
        }
    }

    void showData() throws Exception{
        Object[] column = {"NAMA", "NIM", "ALAMAT", "NO_TELP", "MOTO"};
        List<Anggota> anggotas = repo.getAnggotas();
        Object[][] data = new Object[anggotas.size()][5];
        int i = 0;
        for(Anggota a : anggotas){
            Object[] arr_data = {a.getNama(), a.getNim(), a.getAlamat(), a.getNo_telp(), a.getMoto()};
            data[i] = arr_data;
            i++;
        }
        tabmode = new DefaultTableModel(data, column);
        table.setModel(tabmode);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tfMoto = new javax.swing.JTextField();
        tfNim = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfTelp = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bSave1 = new javax.swing.JButton();
        bSave2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 50, 610, 340);
        getContentPane().add(tfMoto);
        tfMoto.setBounds(190, 250, 180, 35);
        getContentPane().add(tfNim);
        tfNim.setBounds(190, 90, 180, 35);
        getContentPane().add(tfNama);
        tfNama.setBounds(190, 130, 180, 35);
        getContentPane().add(tfTelp);
        tfTelp.setBounds(190, 170, 180, 35);
        getContentPane().add(tfAlamat);
        tfAlamat.setBounds(190, 210, 180, 35);

        bSave.setText("save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave);
        bSave.setBounds(50, 350, 90, 40);

        jLabel1.setText("moto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 250, 130, 30);

        jLabel2.setText("nim");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 130, 30);

        jLabel3.setText("nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 140, 30);

        jLabel4.setText("no_telp");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 140, 30);

        jLabel5.setText("alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 140, 30);

        bSave1.setText("update");
        bSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSave1ActionPerformed(evt);
            }
        });
        getContentPane().add(bSave1);
        bSave1.setBounds(160, 350, 90, 40);

        bSave2.setText("delete");
        bSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSave2ActionPerformed(evt);
            }
        });
        getContentPane().add(bSave2);
        bSave2.setBounds(270, 350, 90, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
         try {
            Anggota a = new Anggota();
            a.setNama(tfNama.getText());
            a.setNim(tfNim.getText());
            a.setAlamat(tfAlamat.getText());
            a.setNo_telp(Integer.parseInt(tfTelp.getText()));
            a.setMoto(tfMoto.getText());
            
            repo.save(a);
            showData();
        } catch (Exception e) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bSaveActionPerformed

    private void bSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSave1ActionPerformed
        try {
            Anggota a = new Anggota();
            a.setNama(tfNama.getText());
            a.setNim(tfNim.getText());
            a.setAlamat(tfAlamat.getText());
            a.setNo_telp(Integer.parseInt(tfTelp.getText()));
            a.setMoto(tfMoto.getText());
            
            repo.update(a);
            showData();
        } catch (Exception e) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bSave1ActionPerformed

    private void bSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSave2ActionPerformed
        try {
            repo.delete(tfNim.getText());
            showData();
        } catch (Exception e) {
            Logger.getLogger(ui.class.getName()).log(Level.SEVERE, null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bSave2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSave1;
    private javax.swing.JButton bSave2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfMoto;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNim;
    private javax.swing.JTextField tfTelp;
    // End of variables declaration//GEN-END:variables
}
